In [50]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import json as JSON
import requests
import time

#Pandas Options
pd.set_option('display.max_columns', None)
pd.options.display.max_rows = 999
pd.options.display.float_format = '{:,.2f}'.format

In [4]:
#API Key
betsapi_key = "*INSERT KEY*"

In [82]:
#EVENT HISTORY

#Getting total pages
event_json = requests.get('https://api.betsapi.com/v2/events/ended?sport_id=1&token={}&league_id={}'.format(betsapi_key,'155')).json()
event_df = pd.io.json.json_normalize(event_json)
total_pages = int(event_df['pager.total']//event_df['pager.per_page']) + 2

#List of odds to concat
live_odds_dfs = []

#Looping page by page
for page_number in np.arange(0, total_pages, 1):
    event_json = requests.get('https://api.betsapi.com/v2/events/ended?sport_id=1&token={}&league_id={}&page={}&source=betfair'.format(betsapi_key, '155', page_number)).json()
    event_df = pd.io.json.json_normalize(event_json['results'])
    
    for key, row in event_df.iterrows():
        #Status
        print ('PAGE {}: Processing the Match {} x {}...'.format(page_number, row['home.name'], row['away.name']), end='\r')
        #Odds history
        odds_json = requests.get('https://api.betsapi.com/v1/event/odds?token={}&event_id={}'.format(betsapi_key,row['id'])).json()
        odds_df = pd.io.json.json_normalize(odds_json['results']['1_1'])
        
        #Skip if is empty
        if len(odds_df) == 0:
            continue
        
        #Adding useful info
        odds_df['home_team'] = row['home.name']
        odds_df['away_team'] = row['away.name']
        odds_df['match_date'] = row['time']
        odds_df['match_api_id'] = row['id']
        
        #Appending
        live_odds_dfs.append(odds_df)
        

#Concatenating
live_odds = pd.concat(live_odds_dfs)
live_odds.dropna(inplace=True, subset=['away_od', 'draw_od', 'home_od'])
live_odds.reset_index(drop=True, inplace=True)
print ('The live_odds DataFrame has {} lines'.format(len(live_odds)))
display(live_odds.head())
display(live_odds.tail())

The live_odds DataFrame has 115589 linesfe x America MG...se....ense...

,add_time,away_od,draw_od,home_od,id,ss,time_str,home_team,away_team,match_date,match_api_id
0,1536526546,501.000,26.000,1.008,24220898,1-0,94,Internacional,Gremio,1536519600,637876
1,1536526540,501.000,26.000,1.010,24220895,1-0,94,Internacional,Gremio,1536519600,637876
2,1536526519,501.000,23.000,1.012,24220881,1-0,94,Internacional,Gremio,1536519600,637876
3,1536526499,501.000,21.000,1.015,24220867,1-0,93,Internacional,Gremio,1536519600,637876
4,1536526460,501.000,19.000,1.020,24220836,1-0,93,Internacional,Gremio,1536519600,637876

,add_time,away_od,draw_od,home_od,id,ss,time_str,home_team,away_team,match_date,match_api_id
115584,1472393972,9.000,4.000,1.400,10826,0:0,18,Santos,Figueirense,1472392800,345
115585,1472393596,8.500,4.000,1.400,10607,0:0,12,Santos,Figueirense,1472392800,345
115586,1472393369,8.000,4.000,1.444,10484,0:0,8,Santos,Figueirense,1472392800,345
115587,1472393086,8.000,4.333,1.444,10359,0:0,3,Santos,Figueirense,1472392800,345
115588,1472393002,8.500,4.333,1.400,10328,0:0,2,Santos,Figueirense,1472392800,345

In [95]:
#Exporting to csv
path = "C:/Users/Humberto/Google Drive/Clube da aposta/Analise de dados/Machine Learning Applied in Soccer/"
live_odds.to_csv(path + 'sas_live_odds.csv', sep=',', encoding='utf-8')